apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: kafka
  source:
    path: argocd/manifests/kafka
    repoURL: https://github.com/piomin/sample-terraform-kubernetes-argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-helm
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  source:
    repoURL: 'https://metallb.github.io/metallb'
    targetRevision: 0.13.12
    chart: metallb
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true